# Generated by Django 3.2.16 on 2022-11-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221123_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('G', 'Grocery'), ('M', 'Mobiles'), ('F', 'Fashion'), ('E', 'Electronics'), ('H', 'Home'), ('P', 'Personal Care'), ('A', 'Appliances'), ('T', 'Toys and Baby'), ('S', 'Sports'), ('B', 'Bikes and Cars')], max_length=2),
        ),
    ]
